# File 1: .github/workflows/build.yml
# This workflow runs on push and then triggers the deploy workflow

name: Build and Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          sleep 2
          echo "Dependencies installed!"
      
      - name: Run tests
        run: |
          echo "Running tests..."
          sleep 3
          echo "All tests passed!"
      
      - name: Build application
        run: |
          echo "Building application..."
          sleep 2
          echo "Build completed successfully!"
  
  trigger-deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Trigger deployment workflow
        uses: actions/github-script@v7
        with:
          script: |
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deploy.yml',
              ref: 'main',
              inputs: {
                environment: 'production',
                version: context.sha.substring(0, 7),
                triggered_by: 'build-workflow'
              }
            });
            console.log('Deploy workflow triggered successfully!');

---

# File 2: .github/workflows/deploy.yml
# This workflow gets triggered by the build workflow

name: Deploy Application
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      version:
        description: 'Version to deploy'
        required: true
        default: 'latest'
        type: string
      triggered_by:
        description: 'What triggered this deployment'
        required: false
        default: 'manual'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Display deployment info
        run: |
          echo "🚀 Starting deployment..."
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Version: ${{ github.event.inputs.version }}"
          echo "Triggered by: ${{ github.event.inputs.triggered_by }}"
          echo "Commit SHA: ${{ github.sha }}"
      
      - name: Deploy to ${{ github.event.inputs.environment }}
        run: |
          echo "Deploying to ${{ github.event.inputs.environment }} environment..."
          sleep 3
          echo "Deployment to ${{ github.event.inputs.environment }} completed!"
      
      - name: Verify deployment
        run: |
          echo "Verifying deployment..."
          sleep 2
          echo "✅ Deployment verification successful!"
      
      - name: Notify completion
        run: |
          echo
