# File 1: .github/workflows/build.yml
# This workflow runs on push and then triggers the deploy workflow

name: Build and Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          sleep 2
          echo "Dependencies installed!"
      
      - name: Run tests
        run: |
          echo "Running tests..."
          sleep 3
          echo "All tests passed!"
      
      - name: Build application
        run: |
          echo "Building application..."
          sleep 2
          echo "Build completed successfully!"
  
  trigger-deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Trigger deployment workflow
        uses: actions/github-script@v7
        with:
          script: |
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deploy.yml',
              ref: 'main',
              inputs: {
                environment: 'production',
                version: context.sha.substring(0, 7),
                triggered_by: 'build-workflow'
              }
            });
            console.log('Deploy workflow triggered successfully!');
