name: Second Workflow
on:
  workflow_run:
    workflows: ["First Workflow"]
    types: [completed]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Hello from Second Workflow!"
      
      - name: Step 2
        run: echo "Second workflow was triggered by first workflow!"
