name: Deploy Application
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      version:
        description: 'Version to deploy'
        required: true
        default: 'latest'
        type: string
      triggered_by:
        description: 'What triggered this deployment'
        required: false
        default: 'manual'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Display deployment info
        run: |
          echo "🚀 Starting deployment..."
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Version: ${{ github.event.inputs.version }}"
          echo "Triggered by: ${{ github.event.inputs.triggered_by }}"
          echo "Commit SHA: ${{ github.sha }}"
      
      - name: Deploy to ${{ github.event.inputs.environment }}
        run: |
          echo "Deploying to ${{ github.event.inputs.environment }} environment..."
          sleep 3
          echo "Deployment to ${{ github.event.inputs.environment }} completed!"
      
      - name: Verify deployment
        run: |
          echo "Verifying deployment..."
          sleep 2
          echo "✅ Deployment verification successful!"
      
      - name: Notify completion
        run: |
          echo "🎉 Deployment completed successfully!"
          echo "Version ${{ github.event.inputs.version }} is now live in ${{ github.event.inputs.environment }}!"
