name: First Workflow
on:
  push: 

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Hello from First Workflow!"
      
      - name: Step 2
        run: echo "First workflow is completing..."
