name: Manual Trigger with Inputs
 
on:

  workflow_disptach:

    inputs:

      name:

        description: 'Your name'

        required: true

        default: 'Developer'

      environment:

        description: 'Deployment environment'

        required: true

        default: 'staging'

        type: choice

        options:

          - staging

          - production
 
jobs:

  greet-user:

    runs-on: ubuntu-latest

    steps:

      - name: Print greeting

        run: |

          echo "Hello, ${{ github.event.inputs.name }}!"

          echo "Deploying to the '${{ github.event.inputs.environment }}' environment."

 
